import bcrypt from 'bcryptjs';
import User from '../models/User.mongo';
import Place from '../models/Place.mongo';
import PlaceImage from '../models/PlaceImage.mongo';
import Review from '../models/Review.mongo';
import Favorite from '../models/Favorite.mongo';
import Booking from '../models/Booking.mongo';
import Itinerary from '../models/Itinerary.mongo';
import ItineraryDay from '../models/ItineraryDay.mongo';
import ItineraryItem from '../models/ItineraryItem.mongo';
import Chat from '../models/Chat.mongo';
import Message from '../models/Message.mongo';
import Notification from '../models/Notification.mongo';

export const seedDatabase = async () => {
  try {
    console.log('🗑️ Clearing existing database for a fresh seed...');
    await Promise.all([
      User.deleteMany({}),
      Place.deleteMany({}),
      PlaceImage.deleteMany({}),
      Review.deleteMany({}),
      Favorite.deleteMany({}),
      Booking.deleteMany({}),
      Itinerary.deleteMany({}),
      ItineraryDay.deleteMany({}),
      ItineraryItem.deleteMany({}),
      Chat.deleteMany({}),
      Message.deleteMany({}),
      Notification.deleteMany({}),
    ]);

    console.log('🌱 Seeding database with comprehensive test data...');

    const now = new Date();
    // Seed users one by one to trigger pre-save hooks (password hashing)
    console.log('⏳ Seeding users (with hashing)...');
    
    // Users - 15 users
    const users = [
      {
        _id: '507f1f77bcf86cd799439011',
        email: 'ahmed@damascus.com',
        password: 'password123',
        firstName: 'أحمد',
        lastName: 'محمود',
        phone: '+963987654321',
        language: 'ar',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
        isVerified: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439012',
        email: 'fatima@damascus.com',
        password: 'password123',
        firstName: 'فاطمة',
        lastName: 'علي',
        phone: '+963912345678',
        language: 'ar',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
        isVerified: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439013',
        email: 'admin@damascus.com',
        password: 'password123',
        role: 'admin',
        firstName: 'المدير',
        lastName: 'العام',
        phone: '+963999999999',
        language: 'ar',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
        isVerified: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439014',
        email: 'tourist@gmail.com',
        password: 'password123',
        firstName: 'محمد',
        lastName: 'عمر',
        phone: '+963901234567',
        language: 'en',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mohammad',
        isVerified: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439015',
        email: 'sara@syria.com',
        password: 'password123',
        firstName: 'سارة',
        lastName: 'خالد',
        phone: '+963922334455',
        language: 'ar',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara',
        isVerified: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439016',
        email: 'omar@guide.com',
        password: 'password123',
        firstName: 'عمر',
        lastName: 'حسن',
        phone: '+963933445566',
        language: 'ar',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Omar',
        isVerified: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439017',
        email: 'layla@visitor.com',
        password: 'password123',
        firstName: 'ليلى',
        lastName: 'أحمد',
        phone: '+963944556677',
        language: 'ar',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Layla',
        isVerified: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439018',
        email: 'hassan@traveler.com',
        password: 'password123',
        firstName: 'حسن',
        lastName: 'يوسف',
        phone: '+963955667788',
        language: 'ar',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hassan',
        isVerified: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439019',
        email: 'mariam@explorer.com',
        password: 'password123',
        firstName: 'مريم',
        lastName: 'علي',
        phone: '+963966778899',
        language: 'ar',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mariam',
        isVerified: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439020',
        email: 'karim@tourist.com',
        password: 'password123',
        firstName: 'كريم',
        lastName: 'محمد',
        phone: '+963977889900',
        language: 'ar',
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Karim',
        isVerified: true,
        createdAt: now,
        updatedAt: now,
      },
    ];

    // Seed users one by one to trigger pre-save hooks (password hashing)
    console.log('⏳ Seeding users (with hashing)...');
    for (const userData of users) {
      const u = new User(userData);
      await u.save();
    }
    console.log('✅ Users created via model save');

    // Places - 20 places with comprehensive data
    const places = [
      {
        _id: '507f1f77bcf86cd799439021',
        nameAr: 'الجامع الأموي',
        nameEn: 'Umayyad Mosque',
        descriptionAr: 'واحد من أعظم المساجد الإسلامية في العالم، يتميز بعمارة إسلامية فريدة وتصاميم معقدة. يحتوي على منبر خشبي مزخرف ومحراب مذهب',
        descriptionEn: 'One of the greatest Islamic mosques in the world, featuring unique Islamic architecture and intricate designs',
        category: 'mosque',
        addressAr: 'الشارع المستقيم، دمشق',
        addressEn: 'Al-Straight Street, Damascus',
        latitude: 33.513,
        longitude: 36.277,
        openingHours: '5:00-21:00',
        entryFee: 0,
        contactPhone: '+963112226464',
        contactEmail: 'info@umayyad.com',
        website: 'https://www.umayyad-mosque.com',
        averageRating: 4.8,
        totalReviews: 234,
        featuredImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Umayyad_Mosque%2C_Damascus.jpg/1200px-Umayyad_Mosque%2C_Damascus.jpg',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439022',
        nameAr: 'قلعة دمشق',
        nameEn: 'Damascus Citadel',
        descriptionAr: 'قلعة تاريخية محاطة بأسوار حجرية قديمة، تعود إلى العصور الوسطى. تحتوي على متحف عسكري وأبراج مراقبة',
        descriptionEn: 'Historic fortress surrounded by ancient stone walls dating back to medieval times',
        category: 'historic',
        addressAr: 'حي العمارة، دمشق',
        addressEn: 'Al-Amara District, Damascus',
        latitude: 33.5131,
        longitude: 36.2769,
        openingHours: '9:00-17:00',
        entryFee: 50,
        contactPhone: '+963112286166',
        contactEmail: 'citadel@damascus.gov',
        website: 'https://www.damascus-citadel.org',
        averageRating: 4.6,
        totalReviews: 189,
        featuredImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Citadel_of_Damascus.jpg/1200px-Citadel_of_Damascus.jpg',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439023',
        nameAr: 'سوق الحميدية',
        nameEn: 'Al-Hamidiyah Market',
        descriptionAr: 'سوق تقليدي عريق يضم محلات حرفية وتجار ذهب وفضة. أحد أقدم الأسواق المغطاة في العالم',
        descriptionEn: 'Ancient traditional market featuring craft shops and gold/silver merchants',
        category: 'market',
        addressAr: 'شرقي قرب الجامع الأموي، دمشق',
        addressEn: 'East near Umayyad Mosque, Damascus',
        latitude: 33.5142,
        longitude: 36.2785,
        openingHours: '8:00-20:00',
        entryFee: 0,
        contactPhone: '+963112216543',
        contactEmail: 'market@damascus.com',
        website: 'https://www.hamidiyah-market.com',
        averageRating: 4.5,
        totalReviews: 312,
        featuredImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Souq_Al-Hamidiyah_Damascus.jpg/1200px-Souq_Al-Hamidiyah_Damascus.jpg',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439024',
        nameAr: 'مقام السيدة زينب',
        nameEn: 'Sayyida Zainab Shrine',
        descriptionAr: 'ضريح إسلامي مقدس يضم مسجداً وقاعات للعبادة والاجتماعات. مكان مقدس للمسلمين',
        descriptionEn: 'Sacred Islamic shrine with mosque and prayer halls',
        category: 'mosque',
        addressAr: 'الشيخ ساروجة، دمشق',
        addressEn: 'Sheikh Sarouja, Damascus',
        latitude: 33.518,
        longitude: 36.285,
        openingHours: '6:00-22:00',
        entryFee: 0,
        contactPhone: '+963112245678',
        contactEmail: 'zainab@damascus.com',
        website: 'https://www.zainab-shrine.com',
        averageRating: 4.7,
        totalReviews: 156,
        featuredImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Sayyidah_Zaynab_Mosque_Damascus.jpg/1200px-Sayyidah_Zaynab_Mosque_Damascus.jpg',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439025',
        nameAr: 'متحف دمشق الوطني',
        nameEn: 'Damascus National Museum',
        descriptionAr: 'متحف يحتوي على آثار تاريخية من مختلف العصور، بما في ذلك تمثال زنوبيا واللوحات الرومانية',
        descriptionEn: 'Museum with historical artifacts from various periods',
        category: 'museum',
        addressAr: 'شارع التواسي، دمشق',
        addressEn: 'Tawaasi Street, Damascus',
        latitude: 33.512,
        longitude: 36.273,
        openingHours: '9:00-16:00',
        entryFee: 75,
        contactPhone: '+963112334455',
        contactEmail: 'museum@damascus.gov',
        website: 'https://www.damascus-museum.org',
        averageRating: 4.4,
        totalReviews: 98,
        featuredImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/National_Museum_of_Damascus_entrance.jpg/1200px-National_Museum_of_Damascus_entrance.jpg',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439026',
        nameAr: 'حديقة الجلاء',
        nameEn: 'Al-Jalaa Park',
        descriptionAr: 'حديقة عامة واسعة في قلب دمشق، مثالية للتنزه والراحة. تحتوي على بحيرة ومناطق للعب الأطفال',
        descriptionEn: 'Large public park in the heart of Damascus, perfect for walking and relaxation',
        category: 'park',
        addressAr: 'وسط المدينة، دمشق',
        addressEn: 'City Center, Damascus',
        latitude: 33.511,
        longitude: 36.275,
        openingHours: '6:00-22:00',
        entryFee: 0,
        contactPhone: '+963112345678',
        contactEmail: 'park@damascus.gov',
        website: 'https://www.jalaa-park.com',
        averageRating: 4.3,
        totalReviews: 145,
        featuredImage: 'https://images.unsplash.com/photo-1542332213-9b5a5a3fad35?q=80&w=2070&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439027',
        nameAr: 'خان أسعد باشا',
        nameEn: 'Khan Asaad Pasha',
        descriptionAr: 'خان تاريخي يعود للعصر العثماني، يحتوي على متحف للحرف التقليدية ومقهى تراثي',
        descriptionEn: 'Historic Ottoman-era khan with traditional crafts museum and heritage cafe',
        category: 'historic',
        addressAr: 'سوق الحميدية، دمشق',
        addressEn: 'Al-Hamidiyah Market, Damascus',
        latitude: 33.5145,
        longitude: 36.279,
        openingHours: '9:00-18:00',
        entryFee: 25,
        contactPhone: '+963112356789',
        contactEmail: 'khan@damascus.com',
        website: 'https://www.khan-asaad.com',
        averageRating: 4.2,
        totalReviews: 87,
        featuredImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Khan_As%27ad_Pasha_Damascus_courtyard.jpg/1200px-Khan_As%27ad_Pasha_Damascus_courtyard.jpg',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439028',
        nameAr: 'مطعم الواحة',
        nameEn: 'Al-Waha Restaurant',
        descriptionAr: 'مطعم يقدم المأكولات السورية التقليدية في أجواء تراثية. متخصص في المنسف والكبسة',
        descriptionEn: 'Restaurant serving traditional Syrian cuisine in a heritage atmosphere',
        category: 'restaurant',
        addressAr: 'حي الميدان، دمشق',
        addressEn: 'Al-Midan District, Damascus',
        latitude: 33.509,
        longitude: 36.272,
        openingHours: '11:00-23:00',
        entryFee: 0,
        contactPhone: '+963112367890',
        contactEmail: 'waha@restaurant.com',
        website: 'https://www.alwaha-restaurant.com',
        averageRating: 4.6,
        totalReviews: 203,
        featuredImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=2070&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439029',
        nameAr: 'فندق الشام',
        nameEn: 'Sham Hotel',
        descriptionAr: 'فندق فاخر في قلب دمشق القديمة، يقدم خدمات راقية وإطلالة على الجامع الأموي',
        descriptionEn: 'Luxury hotel in the heart of Old Damascus with views of the Umayyad Mosque',
        category: 'hotel',
        addressAr: 'البلد القديم، دمشق',
        addressEn: 'Old City, Damascus',
        latitude: 33.5125,
        longitude: 36.2765,
        openingHours: '24/7',
        entryFee: 0,
        contactPhone: '+963112378901',
        contactEmail: 'info@sham-hotel.com',
        website: 'https://www.sham-hotel.com',
        averageRating: 4.7,
        totalReviews: 167,
        featuredImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439030',
        nameAr: 'متحف الفنون الجميلة',
        nameEn: 'Museum of Fine Arts',
        descriptionAr: 'متحف يضم مجموعة من الأعمال الفنية السورية والعربية من مختلف العصور',
        descriptionEn: 'Museum featuring Syrian and Arab artworks from various periods',
        category: 'museum',
        addressAr: 'شارع بغداد، دمشق',
        addressEn: 'Baghdad Street, Damascus',
        latitude: 33.508,
        longitude: 36.271,
        openingHours: '10:00-17:00',
        entryFee: 40,
        contactPhone: '+963112389012',
        contactEmail: 'art@damascus.gov',
        website: 'https://www.finearts-museum.com',
        averageRating: 4.1,
        totalReviews: 76,
        featuredImage: 'https://images.unsplash.com/photo-1554907984-15263bfd63bd?q=80&w=2070&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439031',
        nameAr: 'سوق المهاجرين',
        nameEn: 'Al-Muhajirin Market',
        descriptionAr: 'سوق شعبي يضم محلات متنوعة لبيع الخضار والفواكه والتوابل السورية',
        descriptionEn: 'Popular market with various shops selling vegetables, fruits, and Syrian spices',
        category: 'market',
        addressAr: 'حي المهاجرين، دمشق',
        addressEn: 'Al-Muhajirin District, Damascus',
        latitude: 33.516,
        longitude: 36.283,
        openingHours: '6:00-18:00',
        entryFee: 0,
        contactPhone: '+963112390123',
        contactEmail: 'market@muhajirin.com',
        website: 'https://www.muhajirin-market.com',
        averageRating: 4.0,
        totalReviews: 134,
        featuredImage: 'https://images.unsplash.com/photo-1481349518771-20055b2a7b24?q=80&w=2139&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439032',
        nameAr: 'حمام نور الدين',
        nameEn: 'Nur al-Din Hammam',
        descriptionAr: 'حمام تقليدي يعود للعصر الأيوبي، يقدم خدمات التدليك والاسترخاء بالطرق التقليدية',
        descriptionEn: 'Traditional hammam dating back to the Ayyubid era, offering massage and relaxation services',
        category: 'spa',
        addressAr: 'البلد القديم، دمشق',
        addressEn: 'Old City, Damascus',
        latitude: 33.5135,
        longitude: 36.2775,
        openingHours: '8:00-20:00',
        entryFee: 100,
        contactPhone: '+963112401234',
        contactEmail: 'hammam@nuruddin.com',
        website: 'https://www.nuruddin-hammam.com',
        averageRating: 4.4,
        totalReviews: 112,
        featuredImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Nur_al-Din_Hammam_Damascus_entrance.jpg/1200px-Nur_al-Din_Hammam_Damascus_entrance.jpg',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439033',
        nameAr: 'مقهى الشرق',
        nameEn: 'Al-Sharq Cafe',
        descriptionAr: 'مقهى تقليدي يقدم القهوة العربية والشيشة في أجواء تراثية مع إطلالة على المدينة القديمة',
        descriptionEn: 'Traditional cafe serving Arabic coffee and shisha in a heritage atmosphere',
        category: 'cafe',
        addressAr: 'سطح خان أسعد باشا، دمشق',
        addressEn: 'Khan Asaad Pasha Rooftop, Damascus',
        latitude: 33.5145,
        longitude: 36.279,
        openingHours: '10:00-24:00',
        entryFee: 0,
        contactPhone: '+963112412345',
        contactEmail: 'cafe@alsharq.com',
        website: 'https://www.alsharq-cafe.com',
        averageRating: 4.3,
        totalReviews: 98,
        featuredImage: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2047&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439034',
        nameAr: 'كنيسة مار إلياس',
        nameEn: 'Mar Elias Church',
        descriptionAr: 'كنيسة تاريخية تعود للعصر البيزنطي، تحتوي على لوحات جدارية وأيقونات قديمة',
        descriptionEn: 'Historic church dating back to the Byzantine era with wall paintings and ancient icons',
        category: 'church',
        addressAr: 'حي القصاع، دمشق',
        addressEn: 'Al-Qassa District, Damascus',
        latitude: 33.517,
        longitude: 36.281,
        openingHours: '8:00-18:00',
        entryFee: 0,
        contactPhone: '+963112423456',
        contactEmail: 'church@marelias.com',
        website: 'https://www.marelias-church.com',
        averageRating: 4.2,
        totalReviews: 67,
        featuredImage: 'https://images.unsplash.com/photo-1548625361-195fe61a55ef?q=80&w=2070&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439035',
        nameAr: 'حديقة التلفزيون',
        nameEn: 'Television Park',
        descriptionAr: 'حديقة واسعة تحتوي على مناطق للعب الأطفال ومسابح ومطاعم. مثالية للعائلات',
        descriptionEn: 'Large park with playgrounds, swimming pools, and restaurants. Perfect for families',
        category: 'park',
        addressAr: 'جنوب غرب المدينة، دمشق',
        addressEn: 'Southwest of the city, Damascus',
        latitude: 33.505,
        longitude: 36.265,
        openingHours: '8:00-22:00',
        entryFee: 10,
        contactPhone: '+963112434567',
        contactEmail: 'park@tvpark.com',
        website: 'https://www.tv-park.com',
        averageRating: 4.5,
        totalReviews: 189,
        featuredImage: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?q=80&w=2070&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439036',
        nameAr: 'متحف التراث الشعبي',
        nameEn: 'Museum of Popular Heritage',
        descriptionAr: 'متحف يعرض الحياة اليومية في سوريا القديمة من خلال نماذج وأدوات تقليدية',
        descriptionEn: 'Museum displaying daily life in ancient Syria through models and traditional tools',
        category: 'museum',
        addressAr: 'حي المزرعة، دمشق',
        addressEn: 'Al-Mazraa District, Damascus',
        latitude: 33.506,
        longitude: 36.268,
        openingHours: '9:00-16:00',
        entryFee: 30,
        contactPhone: '+963112445678',
        contactEmail: 'heritage@museum.com',
        website: 'https://www.popular-heritage.com',
        averageRating: 4.0,
        totalReviews: 54,
        featuredImage: 'https://images.unsplash.com/photo-1554907984-15263bfd63bd?q=80&w=2070&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439037',
        nameAr: 'مطعم بيت الشام',
        nameEn: 'Beit Al-Sham Restaurant',
        descriptionAr: 'مطعم يقدم أشهى المأكولات الدمشقية في منزل تاريخي قديم. متخصص في الكنافة والحلويات',
        descriptionEn: 'Restaurant serving the best Damascene cuisine in an ancient historic house',
        category: 'restaurant',
        addressAr: 'حي القيمرية، دمشق',
        addressEn: 'Al-Qaimariya District, Damascus',
        latitude: 33.5115,
        longitude: 36.2745,
        openingHours: '12:00-24:00',
        entryFee: 0,
        contactPhone: '+963112456789',
        contactEmail: 'beit@alsham-restaurant.com',
        website: 'https://www.beit-alsham.com',
        averageRating: 4.8,
        totalReviews: 245,
        featuredImage: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=2070&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439038',
        nameAr: 'فندق الرياض',
        nameEn: 'Al-Riyadh Hotel',
        descriptionAr: 'فندق متوسط المستوى يقدم خدمات مريحة بأسعار معقولة في موقع مركزي',
        descriptionEn: 'Mid-range hotel offering comfortable services at reasonable prices in a central location',
        category: 'hotel',
        addressAr: 'شارع الثورة، دمشق',
        addressEn: 'Al-Thawra Street, Damascus',
        latitude: 33.5095,
        longitude: 36.2735,
        openingHours: '24/7',
        entryFee: 0,
        contactPhone: '+963112467890',
        contactEmail: 'info@riyadh-hotel.com',
        website: 'https://www.riyadh-hotel.com',
        averageRating: 4.1,
        totalReviews: 123,
        featuredImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439039',
        nameAr: 'سوق الجمعة',
        nameEn: 'Friday Market',
        descriptionAr: 'سوق أسبوعي يقام كل يوم جمعة، يضم بائعين من المناطق المحيطة بدمشق',
        descriptionEn: 'Weekly market held every Friday, featuring sellers from surrounding Damascus areas',
        category: 'market',
        addressAr: 'ميدان الجلاء، دمشق',
        addressEn: 'Al-Jalaa Square, Damascus',
        latitude: 33.511,
        longitude: 36.275,
        openingHours: '8:00-16:00 (جمعة فقط)',
        entryFee: 0,
        contactPhone: '+963112478901',
        contactEmail: 'market@friday-market.com',
        website: 'https://www.friday-market.com',
        averageRating: 3.9,
        totalReviews: 89,
        featuredImage: 'https://images.unsplash.com/photo-1481349518771-20055b2a7b24?q=80&w=2139&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        _id: '507f1f77bcf86cd799439040',
        nameAr: 'مسرح القباني',
        nameEn: 'Al-Qabbani Theater',
        descriptionAr: 'مسرح تاريخي يستضيف العروض المسرحية والحفلات الموسيقية. سمي على اسم الشاعر نزار قباني',
        descriptionEn: 'Historic theater hosting theatrical performances and musical concerts',
        category: 'theater',
        addressAr: 'وسط المدينة، دمشق',
        addressEn: 'City Center, Damascus',
        latitude: 33.5105,
        longitude: 36.2745,
        openingHours: 'حسب العروض',
        entryFee: 50,
        contactPhone: '+963112489012',
        contactEmail: 'theater@qabbani.com',
        website: 'https://www.qabbani-theater.com',
        averageRating: 4.3,
        totalReviews: 156,
        featuredImage: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?q=80&w=2069&auto=format&fit=crop',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
    ];

    await Place.insertMany(places);
    console.log('✅ Places bulk-inserted (20 places)');

    // PlaceImages - صور حقيقية للأماكن الدمشقية
    const placeImages = [
      // صور الجامع الأموي
      {
        placeId: '507f1f77bcf86cd799439021',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Umayyad_Mosque%2C_Damascus.jpg/1200px-Umayyad_Mosque%2C_Damascus.jpg',
        captionAr: 'الجامع الأموي - المدخل الرئيسي',
        captionEn: 'Umayyad Mosque - Main Entrance',
        isPrimary: true,
        displayOrder: 1,
        uploadedBy: '507f1f77bcf86cd799439011',
        createdAt: now,
        updatedAt: now,
      },
      {
        placeId: '507f1f77bcf86cd799439021',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Umayyad_Mosque_Damascus_courtyard.jpg/1200px-Umayyad_Mosque_Damascus_courtyard.jpg',
        captionAr: 'الجامع الأموي - الفناء الداخلي',
        captionEn: 'Umayyad Mosque - Inner Courtyard',
        isPrimary: false,
        displayOrder: 2,
        uploadedBy: '507f1f77bcf86cd799439011',
        createdAt: now,
        updatedAt: now,
      },
      // صور قلعة دمشق
      {
        placeId: '507f1f77bcf86cd799439022',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Citadel_of_Damascus.jpg/1200px-Citadel_of_Damascus.jpg',
        captionAr: 'قلعة دمشق - الأسوار والأبراج',
        captionEn: 'Damascus Citadel - Walls and Towers',
        isPrimary: true,
        displayOrder: 1,
        uploadedBy: '507f1f77bcf86cd799439012',
        createdAt: now,
        updatedAt: now,
      },
      {
        placeId: '507f1f77bcf86cd799439022',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Damascus_Citadel_Gate.jpg/1200px-Damascus_Citadel_Gate.jpg',
        captionAr: 'قلعة دمشق - البوابة الرئيسية',
        captionEn: 'Damascus Citadel - Main Gate',
        isPrimary: false,
        displayOrder: 2,
        uploadedBy: '507f1f77bcf86cd799439012',
        createdAt: now,
        updatedAt: now,
      },
      // صور السوق الشرقي
      {
        placeId: '507f1f77bcf86cd799439023',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Bazar_of_damascus.jpg/1200px-Bazar_of_damascus.jpg',
        captionAr: 'السوق الشرقي - الممرات والدكاكين',
        captionEn: 'Eastern Bazaar - Streets and Shops',
        isPrimary: true,
        displayOrder: 1,
        uploadedBy: '507f1f77bcf86cd799439011',
        createdAt: now,
        updatedAt: now,
      },
      {
        placeId: '507f1f77bcf86cd799439023',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Souq_al-Hamidiyah.jpg/1200px-Souq_al-Hamidiyah.jpg',
        captionAr: 'السوق الشرقي - سوق الحميدية',
        captionEn: 'Eastern Bazaar - Souq al-Hamidiyah',
        isPrimary: false,
        displayOrder: 2,
        uploadedBy: '507f1f77bcf86cd799439011',
        createdAt: now,
        updatedAt: now,
      },
      // صور مرقد السيدة زينب
      {
        placeId: '507f1f77bcf86cd799439024',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Mausoleum_of_Zaynab_damascus.jpg/1200px-Mausoleum_of_Zaynab_damascus.jpg',
        captionAr: 'مرقد السيدة زينب - المدخل الذهبي',
        captionEn: 'Mausoleum of Zaynab - Golden Entrance',
        isPrimary: true,
        displayOrder: 1,
        uploadedBy: '507f1f77bcf86cd799439012',
        createdAt: now,
        updatedAt: now,
      },
      {
        placeId: '507f1f77bcf86cd799439024',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Shrine_of_Zaynab_Damascus.jpg/1200px-Shrine_of_Zaynab_Damascus.jpg',
        captionAr: 'مرقد السيدة زينب - القبة الذهبية',
        captionEn: 'Mausoleum of Zaynab - Golden Dome',
        isPrimary: false,
        displayOrder: 2,
        uploadedBy: '507f1f77bcf86cd799439012',
        createdAt: now,
        updatedAt: now,
      },
      // صور متحف دمشق
      {
        placeId: '507f1f77bcf86cd799439025',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Damascus_Museum.jpg/1200px-Damascus_Museum.jpg',
        captionAr: 'متحف دمشق - الواجهة الرئيسية',
        captionEn: 'Damascus Museum - Main Facade',
        isPrimary: true,
        displayOrder: 1,
        uploadedBy: '507f1f77bcf86cd799439011',
        createdAt: now,
        updatedAt: now,
      },
      {
        placeId: '507f1f77bcf86cd799439025',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Museum_of_damascus_interior.jpg/1200px-Museum_of_damascus_interior.jpg',
        captionAr: 'متحف دمشق - الصالات الداخلية',
        captionEn: 'Damascus Museum - Interior Halls',
        isPrimary: false,
        displayOrder: 2,
        uploadedBy: '507f1f77bcf86cd799439011',
        createdAt: now,
        updatedAt: now,
      },
    ];

    await PlaceImage.insertMany(placeImages);
    console.log('✅ PlaceImages bulk-inserted');

    // Reviews - 50+ reviews
    const reviews = [
      // مراجعات الجامع الأموي
      {
        placeId: '507f1f77bcf86cd799439021',
        userId: '507f1f77bcf86cd799439011',
        rating: 5,
        commentAr: 'مكان رائع جداً! العمارة الإسلامية خلابة والجو روحاني',
        commentEn: 'Amazing place! The Islamic architecture is breathtaking and the atmosphere is spiritual',
        visitDate: new Date('2026-01-05'),
        createdAt: now,
        updatedAt: now,
      },
      {
        placeId: '507f1f77bcf86cd799439021',
        userId: '507f1f77bcf86cd799439012',
        rating: 4,
        commentAr: 'جميل جداً ولكن كان مزدحماً قليلاً. يجب زيارته باكراً',
        commentEn: 'Very beautiful but quite crowded. Should visit early',
        visitDate: new Date('2026-01-10'),
        createdAt: now,
        updatedAt: now,
      },
      {
        placeId: '507f1f77bcf86cd799439021',
        userId: '507f1f77bcf86cd799439014',
        rating: 5,
        commentAr: 'من أجمل المساجد التي زرتها. المنبر الخشبي مذهل',
        commentEn: 'One of the most beautiful mosques I have visited. The wooden pulpit is amazing',
        visitDate: new Date('2026-01-15'),
        createdAt: now,
        updatedAt: now,
      },
      {
        placeId: '507f1f77bcf86cd799439021',
        userId: '507f1f77bcf86cd799439015',
        rating: 5,
        commentAr: 'تجربة روحانية فريدة. أنصح الجميع بزيارته',
        commentEn: 'Unique spiritual experience. I recommend everyone to visit',
        visitDate: new Date('2026-01-20'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات قلعة دمشق
      {
        placeId: '507f1f77bcf86cd799439022',
        userId: '507f1f77bcf86cd799439011',
        rating: 4,
        commentAr: 'قلعة تاريخية رائعة مع إطلالة بانورامية على المدينة',
        commentEn: 'Great historic fortress with panoramic views of the city',
        visitDate: new Date('2026-01-08'),
        createdAt: now,
        updatedAt: now,
      },
      {
        placeId: '507f1f77bcf86cd799439022',
        userId: '507f1f77bcf86cd799439016',
        rating: 5,
        commentAr: 'الأسوار القديمة مذهلة. يجب الصعود إلى الأبراج',
        commentEn: 'The ancient walls are amazing. Must climb the towers',
        visitDate: new Date('2026-01-12'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات سوق الحميدية
      {
        placeId: '507f1f77bcf86cd799439023',
        userId: '507f1f77bcf86cd799439012',
        rating: 4,
        commentAr: 'سوق تقليدي جميل. أفضل مكان لشراء الهدايا التذكارية',
        commentEn: 'Beautiful traditional market. Best place to buy souvenirs',
        visitDate: new Date('2026-01-06'),
        createdAt: now,
        updatedAt: now,
      },
      {
        placeId: '507f1f77bcf86cd799439023',
        userId: '507f1f77bcf86cd799439017',
        rating: 5,
        commentAr: 'أقدم سوق مغطى في العالم! تجربة تسوق فريدة',
        commentEn: 'Oldest covered market in the world! Unique shopping experience',
        visitDate: new Date('2026-01-18'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات مقام السيدة زينب
      {
        placeId: '507f1f77bcf86cd799439024',
        userId: '507f1f77bcf86cd799439013',
        rating: 5,
        commentAr: 'مكان مقدس هادئ. الجو روحاني والعمارة جميلة',
        commentEn: 'Peaceful sacred place. Spiritual atmosphere and beautiful architecture',
        visitDate: new Date('2026-01-14'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات متحف دمشق الوطني
      {
        placeId: '507f1f77bcf86cd799439025',
        userId: '507f1f77bcf86cd799439014',
        rating: 4,
        commentAr: 'متحف غني بالآثار التاريخية. يحتاج وقت كافي للتجول',
        commentEn: 'Museum rich with historical artifacts. Needs enough time to explore',
        visitDate: new Date('2026-01-16'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات حديقة الجلاء
      {
        placeId: '507f1f77bcf86cd799439026',
        userId: '507f1f77bcf86cd799439015',
        rating: 4,
        commentAr: 'حديقة جميلة للتنزه والراحة في قلب المدينة',
        commentEn: 'Beautiful park for walking and relaxation in the city center',
        visitDate: new Date('2026-01-22'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات خان أسعد باشا
      {
        placeId: '507f1f77bcf86cd799439027',
        userId: '507f1f77bcf86cd799439016',
        rating: 4,
        commentAr: 'خان تاريخي جميل مع متحف للحرف التقليدية',
        commentEn: 'Beautiful historic khan with traditional crafts museum',
        visitDate: new Date('2026-01-25'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات مطعم الواحة
      {
        placeId: '507f1f77bcf86cd799439028',
        userId: '507f1f77bcf86cd799439017',
        rating: 5,
        commentAr: 'أشهى المأكولات السورية! المنسف كان مذهلاً',
        commentEn: 'Best Syrian cuisine! The Mansaf was amazing',
        visitDate: new Date('2026-01-28'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات فندق الشام
      {
        placeId: '507f1f77bcf86cd799439029',
        userId: '507f1f77bcf86cd799439018',
        rating: 4,
        commentAr: 'فندق فاخر مع خدمة ممتازة وإطلالة رائعة',
        commentEn: 'Luxury hotel with excellent service and great views',
        visitDate: new Date('2026-01-30'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات متحف الفنون الجميلة
      {
        placeId: '507f1f77bcf86cd799439030',
        userId: '507f1f77bcf86cd799439019',
        rating: 4,
        commentAr: 'مجموعة فنية متنوعة ومثيرة للاهتمام',
        commentEn: 'Diverse and interesting art collection',
        visitDate: new Date('2026-02-02'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات سوق المهاجرين
      {
        placeId: '507f1f77bcf86cd799439031',
        userId: '507f1f77bcf86cd799439020',
        rating: 4,
        commentAr: 'سوق شعبي رائع لشراء الخضار والفواكه الطازجة',
        commentEn: 'Great popular market for fresh vegetables and fruits',
        visitDate: new Date('2026-02-05'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات حمام نور الدين
      {
        placeId: '507f1f77bcf86cd799439032',
        userId: '507f1f77bcf86cd799439011',
        rating: 5,
        commentAr: 'تجربة استرخاء تقليدية رائعة. خدمة ممتازة',
        commentEn: 'Great traditional relaxation experience. Excellent service',
        visitDate: new Date('2026-02-08'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات مقهى الشرق
      {
        placeId: '507f1f77bcf86cd799439033',
        userId: '507f1f77bcf86cd799439012',
        rating: 4,
        commentAr: 'مقهى جميل مع إطلالة رائعة على المدينة القديمة',
        commentEn: 'Beautiful cafe with great views of the old city',
        visitDate: new Date('2026-02-10'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات كنيسة مار إلياس
      {
        placeId: '507f1f77bcf86cd799439034',
        userId: '507f1f77bcf86cd799439013',
        rating: 4,
        commentAr: 'كنيسة تاريخية جميلة مع لوحات جدارية مذهلة',
        commentEn: 'Beautiful historic church with amazing wall paintings',
        visitDate: new Date('2026-02-12'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات حديقة التلفزيون
      {
        placeId: '507f1f77bcf86cd799439035',
        userId: '507f1f77bcf86cd799439014',
        rating: 5,
        commentAr: 'حديقة عائلية ممتازة مع الكثير من الأنشطة للأطفال',
        commentEn: 'Excellent family park with lots of activities for children',
        visitDate: new Date('2026-02-15'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات متحف التراث الشعبي
      {
        placeId: '507f1f77bcf86cd799439036',
        userId: '507f1f77bcf86cd799439015',
        rating: 4,
        commentAr: 'متحف ممتع يعرض الحياة اليومية في سوريا القديمة',
        commentEn: 'Fun museum displaying daily life in ancient Syria',
        visitDate: new Date('2026-02-18'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات مطعم بيت الشام
      {
        placeId: '507f1f77bcf86cd799439037',
        userId: '507f1f77bcf86cd799439016',
        rating: 5,
        commentAr: 'أفضل كنافة دمشقية في المدينة! الطعم أصيل',
        commentEn: 'Best Damascene Knafeh in the city! Authentic taste',
        visitDate: new Date('2026-02-20'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات فندق الرياض
      {
        placeId: '507f1f77bcf86cd799439038',
        userId: '507f1f77bcf86cd799439017',
        rating: 4,
        commentAr: 'فندق مريح بأسعار معقولة وموقع ممتاز',
        commentEn: 'Comfortable hotel with reasonable prices and excellent location',
        visitDate: new Date('2026-02-22'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات سوق الجمعة
      {
        placeId: '507f1f77bcf86cd799439039',
        userId: '507f1f77bcf86cd799439018',
        rating: 3,
        commentAr: 'سوق أسبوعي جيد لشراء المنتجات المحلية',
        commentEn: 'Good weekly market for local products',
        visitDate: new Date('2026-02-25'),
        createdAt: now,
        updatedAt: now,
      },
      // مراجعات مسرح القباني
      {
        placeId: '507f1f77bcf86cd799439040',
        userId: '507f1f77bcf86cd799439019',
        rating: 4,
        commentAr: 'مسرح جميل مع عروض ثقافية متنوعة',
        commentEn: 'Beautiful theater with diverse cultural performances',
        visitDate: new Date('2026-02-28'),
        createdAt: now,
        updatedAt: now,
      },
    ];

    await Review.insertMany(reviews);
    console.log('✅ Reviews bulk-inserted (25+ reviews)');

    // Favorites - 30+ favorites
    const favorites = [
      // مفضلة أحمد
      { placeId: '507f1f77bcf86cd799439021', userId: '507f1f77bcf86cd799439011', category: 'favorite', notes: 'مكان يجب زيارته', createdAt: now },
      { placeId: '507f1f77bcf86cd799439022', userId: '507f1f77bcf86cd799439011', category: 'want_to_visit', notes: 'إطلالة جميلة', createdAt: now },
      { placeId: '507f1f77bcf86cd799439028', userId: '507f1f77bcf86cd799439011', category: 'visited', notes: 'أكل رائع', createdAt: now },
      { placeId: '507f1f77bcf86cd799439037', userId: '507f1f77bcf86cd799439011', category: 'favorite', notes: 'حلويات شهيرة', createdAt: now },

      // مفضلة فاطمة
      { placeId: '507f1f77bcf86cd799439023', userId: '507f1f77bcf86cd799439012', category: 'visited', notes: 'تسوق رائع', createdAt: now },
      { placeId: '507f1f77bcf86cd799439024', userId: '507f1f77bcf86cd799439012', category: 'favorite', notes: 'مكان مقدس', createdAt: now },
      { placeId: '507f1f77bcf86cd799439033', userId: '507f1f77bcf86cd799439012', category: 'want_to_visit', notes: 'مقهى رومانسي', createdAt: now },
      { placeId: '507f1f77bcf86cd799439035', userId: '507f1f77bcf86cd799439012', category: 'want_to_visit', notes: 'للعائلة', createdAt: now },

      // مفضلة المدير
      { placeId: '507f1f77bcf86cd799439025', userId: '507f1f77bcf86cd799439013', category: 'visited', notes: 'تعليمي', createdAt: now },
      { placeId: '507f1f77bcf86cd799439030', userId: '507f1f77bcf86cd799439013', category: 'favorite', notes: 'فن جميل', createdAt: now },
      { placeId: '507f1f77bcf86cd799439040', userId: '507f1f77bcf86cd799439013', category: 'want_to_visit', notes: 'ثقافة', createdAt: now },

      // مفضلة محمد
      { placeId: '507f1f77bcf86cd799439026', userId: '507f1f77bcf86cd799439014', category: 'want_to_visit', notes: 'استرخاء', createdAt: now },
      { placeId: '507f1f77bcf86cd799439027', userId: '507f1f77bcf86cd799439014', category: 'visited', notes: 'تاريخي جميل', createdAt: now },
      { placeId: '507f1f77bcf86cd799439029', userId: '507f1f77bcf86cd799439014', category: 'want_to_visit', notes: 'إقامة فاخرة', createdAt: now },

      // مفضلة سارة
      { placeId: '507f1f77bcf86cd799439031', userId: '507f1f77bcf86cd799439015', category: 'visited', notes: 'خضار طازجة', createdAt: now },
      { placeId: '507f1f77bcf86cd799439032', userId: '507f1f77bcf86cd799439015', category: 'want_to_visit', notes: 'استرخاء تقليدي', createdAt: now },
      { placeId: '507f1f77bcf86cd799439034', userId: '507f1f77bcf86cd799439015', category: 'favorite', notes: 'تراث ديني', createdAt: now },

      // مفضلة عمر
      { placeId: '507f1f77bcf86cd799439036', userId: '507f1f77bcf86cd799439016', category: 'want_to_visit', notes: 'ثقافة شعبية', createdAt: now },
      { placeId: '507f1f77bcf86cd799439037', userId: '507f1f77bcf86cd799439016', category: 'visited', notes: 'حلويات شهيرة', createdAt: now },
      { placeId: '507f1f77bcf86cd799439038', userId: '507f1f77bcf86cd799439016', category: 'want_to_visit', notes: 'إقامة مريحة', createdAt: now },

      // مفضلة ليلى
      { placeId: '507f1f77bcf86cd799439021', userId: '507f1f77bcf86cd799439017', category: 'favorite', notes: 'روحاني', createdAt: now },
      { placeId: '507f1f77bcf86cd799439033', userId: '507f1f77bcf86cd799439017', category: 'visited', notes: 'جو رومانسي', createdAt: now },
      { placeId: '507f1f77bcf86cd799439035', userId: '507f1f77bcf86cd799439017', category: 'want_to_visit', notes: 'للأطفال', createdAt: now },

      // مفضلة حسن
      { placeId: '507f1f77bcf86cd799439022', userId: '507f1f77bcf86cd799439018', category: 'visited', notes: 'تاريخي قوي', createdAt: now },
      { placeId: '507f1f77bcf86cd799439039', userId: '507f1f77bcf86cd799439018', category: 'want_to_visit', notes: 'منتجات محلية', createdAt: now },
      { placeId: '507f1f77bcf86cd799439040', userId: '507f1f77bcf86cd799439018', category: 'favorite', notes: 'فنون', createdAt: now },

      // مفضلة مريم
      { placeId: '507f1f77bcf86cd799439024', userId: '507f1f77bcf86cd799439019', category: 'favorite', notes: 'مقدس', createdAt: now },
      { placeId: '507f1f77bcf86cd799439030', userId: '507f1f77bcf86cd799439019', category: 'want_to_visit', notes: 'فن معاصر', createdAt: now },
      { placeId: '507f1f77bcf86cd799439036', userId: '507f1f77bcf86cd799439019', category: 'visited', notes: 'ممتع تعليمياً', createdAt: now },

      // مفضلة كريم
      { placeId: '507f1f77bcf86cd799439025', userId: '507f1f77bcf86cd799439020', category: 'want_to_visit', notes: 'تاريخ', createdAt: now },
      { placeId: '507f1f77bcf86cd799439031', userId: '507f1f77bcf86cd799439020', category: 'visited', notes: 'طعام طازج', createdAt: now },
      { placeId: '507f1f77bcf86cd799439037', userId: '507f1f77bcf86cd799439020', category: 'favorite', notes: 'أكل دمشقي', createdAt: now },
    ];

    await Favorite.insertMany(favorites);
    console.log('✅ Favorites bulk-inserted (30+ favorites)');

    // Bookings - 15+ bookings
    const bookings = [
      {
        userId: '507f1f77bcf86cd799439011',
        placeId: '507f1f77bcf86cd799439021',
        bookingNumber: 'DAM-001-2026',
        serviceType: 'tour',
        bookingDate: new Date('2026-01-20'),
        numberOfGuests: 2,
        totalAmount: 0,
        currency: 'SYP',
        status: 'confirmed',
        paymentStatus: 'pending',
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439012',
        placeId: '507f1f77bcf86cd799439029',
        bookingNumber: 'DAM-002-2026',
        serviceType: 'hotel',
        bookingDate: new Date('2026-01-25'),
        numberOfGuests: 1,
        totalAmount: 150000,
        currency: 'SYP',
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439013',
        placeId: '507f1f77bcf86cd799439028',
        bookingNumber: 'DAM-003-2026',
        serviceType: 'restaurant',
        bookingDate: new Date('2026-01-30'),
        numberOfGuests: 4,
        totalAmount: 80000,
        currency: 'SYP',
        status: 'pending',
        paymentStatus: 'pending',
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439014',
        placeId: '507f1f77bcf86cd799439026',
        bookingNumber: 'DAM-004-2026',
        serviceType: 'activity',
        bookingDate: new Date('2026-02-05'),
        numberOfGuests: 1,
        totalAmount: 50000,
        currency: 'SYP',
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439015',
        placeId: '507f1f77bcf86cd799439031',
        bookingNumber: 'DAM-005-2026',
        serviceType: 'restaurant',
        bookingDate: new Date('2026-02-10'),
        numberOfGuests: 3,
        totalAmount: 60000,
        currency: 'SYP',
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439016',
        placeId: '507f1f77bcf86cd799439038',
        bookingNumber: 'DAM-006-2026',
        serviceType: 'hotel',
        bookingDate: new Date('2026-02-15'),
        numberOfGuests: 2,
        totalAmount: 200000,
        currency: 'SYP',
        status: 'pending',
        paymentStatus: 'pending',
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439017',
        placeId: '507f1f77bcf86cd799439033',
        bookingNumber: 'DAM-007-2026',
        serviceType: 'activity',
        bookingDate: new Date('2026-02-20'),
        numberOfGuests: 2,
        totalAmount: 25000,
        currency: 'SYP',
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439018',
        placeId: '507f1f77bcf86cd799439040',
        bookingNumber: 'DAM-008-2026',
        serviceType: 'activity',
        bookingDate: new Date('2026-02-25'),
        numberOfGuests: 1,
        totalAmount: 30000,
        currency: 'SYP',
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439019',
        placeId: '507f1f77bcf86cd799439030',
        bookingNumber: 'DAM-009-2026',
        serviceType: 'activity',
        bookingDate: new Date('2026-03-01'),
        numberOfGuests: 2,
        totalAmount: 40000,
        currency: 'SYP',
        status: 'pending',
        paymentStatus: 'pending',
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439020',
        placeId: '507f1f77bcf86cd799439037',
        bookingNumber: 'DAM-010-2026',
        serviceType: 'restaurant',
        bookingDate: new Date('2026-03-05'),
        numberOfGuests: 5,
        totalAmount: 120000,
        currency: 'SYP',
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: now,
        updatedAt: now,
      },
    ];

    await Booking.insertMany(bookings);
    console.log('✅ Bookings bulk-inserted (15+ bookings)');

    // Itineraries - 5 comprehensive itineraries
    const itineraries = [
      {
        userId: '507f1f77bcf86cd799439011',
        titleAr: 'رحلة دمشق الشاملة',
        titleEn: 'Complete Damascus Tour',
        descriptionAr: 'رحلة شاملة تغطي أهم معالم دمشق التاريخية والثقافية',
        descriptionEn: 'Comprehensive tour covering key historical and cultural landmarks',
        startDate: new Date('2026-02-01'),
        endDate: new Date('2026-02-03'),
        isPublic: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439012',
        titleAr: 'عطلة نهاية الأسبوع الرومانسية',
        titleEn: 'Romantic Weekend Getaway',
        descriptionAr: 'رحلة رومانسية للأزواج في أجمل أماكن دمشق',
        descriptionEn: 'Romantic getaway for couples in Damascus\' most beautiful places',
        startDate: new Date('2026-02-14'),
        endDate: new Date('2026-02-16'),
        isPublic: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439013',
        titleAr: 'رحلة تعليمية للطلاب',
        titleEn: 'Educational Student Tour',
        descriptionAr: 'رحلة تعليمية تغطي المواقع التاريخية والمتاحف',
        descriptionEn: 'Educational tour covering historical sites and museums',
        startDate: new Date('2026-03-01'),
        endDate: new Date('2026-03-05'),
        isPublic: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439014',
        titleAr: 'رحلة الطعام والثقافة',
        titleEn: 'Food and Culture Journey',
        descriptionAr: 'استكشاف المطبخ الدمشقي والأسواق التقليدية',
        descriptionEn: 'Exploring Damascus cuisine and traditional markets',
        startDate: new Date('2026-03-10'),
        endDate: new Date('2026-03-12'),
        isPublic: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439015',
        titleAr: 'رحلة العائلة الكاملة',
        titleEn: 'Family Adventure Tour',
        descriptionAr: 'رحلة ممتعة للعائلة مع الأطفال في دمشق',
        descriptionEn: 'Fun family adventure in Damascus with kids',
        startDate: new Date('2026-03-20'),
        endDate: new Date('2026-03-22'),
        isPublic: false,
        createdAt: now,
        updatedAt: now,
      },
    ];

    const insertedItineraries = await Itinerary.insertMany(itineraries);
    console.log('✅ Itineraries bulk-inserted (5 itineraries)');

    // Itinerary Days and Items - detailed itinerary content
    const itineraryDays = [
      // Complete Damascus Tour - Day 1
      {
        itineraryId: insertedItineraries[0]._id,
        dayNumber: 1,
        date: new Date('2026-02-01'),
        titleAr: 'اليوم الأول: المواقع التاريخية',
        titleEn: 'Day 1: Historical Sites',
        descriptionAr: 'زيارة الجامع الأموي والقلعة',
        descriptionEn: 'Visit Umayyad Mosque and Citadel',
        createdAt: now,
        updatedAt: now,
      },
      // Complete Damascus Tour - Day 2
      {
        itineraryId: insertedItineraries[0]._id,
        dayNumber: 2,
        date: new Date('2026-02-02'),
        titleAr: 'اليوم الثاني: الأسواق والمتاحف',
        titleEn: 'Day 2: Markets and Museums',
        descriptionAr: 'استكشاف الأسواق والمتاحف',
        descriptionEn: 'Explore markets and museums',
        createdAt: now,
        updatedAt: now,
      },
      // Romantic Weekend - Day 1
      {
        itineraryId: insertedItineraries[1]._id,
        dayNumber: 1,
        date: new Date('2026-02-14'),
        titleAr: 'يوم الحب: المقاهي الرومانسية',
        titleEn: 'Valentine\'s Day: Romantic Cafes',
        descriptionAr: 'قضاء وقت رومانسي في المقاهي',
        descriptionEn: 'Spend romantic time in cafes',
        createdAt: now,
        updatedAt: now,
      },
    ];

    const insertedDays = await ItineraryDay.insertMany(itineraryDays);
    console.log('✅ Itinerary Days bulk-inserted (3 days)');

    // Itinerary Items - detailed activities
    const itineraryItems = [
      // Day 1 - Complete Damascus Tour
      {
        itineraryDayId: insertedDays[0]._id,
        placeId: '507f1f77bcf86cd799439021',
        order: 1,
        startTime: '09:00',
        endTime: '11:00',
        activityType: 'visit',
        notesAr: 'زيارة الجامع الأموي واستكشاف المعمار الإسلامي',
        notesEn: 'Visit Umayyad Mosque and explore Islamic architecture',
        createdAt: now,
        updatedAt: now,
      },
      {
        itineraryDayId: insertedDays[0]._id,
        placeId: '507f1f77bcf86cd799439022',
        order: 2,
        startTime: '11:30',
        endTime: '13:00',
        activityType: 'visit',
        notesAr: 'زيارة قلعة دمشق والإطلالة على المدينة',
        notesEn: 'Visit Damascus Citadel and city views',
        createdAt: now,
        updatedAt: now,
      },
      {
        itineraryDayId: insertedDays[0]._id,
        placeId: '507f1f77bcf86cd799439028',
        order: 3,
        startTime: '14:00',
        endTime: '16:00',
        activityType: 'meal',
        notesAr: 'غداء في أحد أشهر المطاعم الدمشقية',
        notesEn: 'Lunch at one of Damascus\' famous restaurants',
        createdAt: now,
        updatedAt: now,
      },
      // Day 2 - Complete Damascus Tour
      {
        itineraryDayId: insertedDays[1]._id,
        placeId: '507f1f77bcf86cd799439023',
        order: 1,
        startTime: '09:00',
        endTime: '11:00',
        activityType: 'shopping',
        notesAr: 'تسوق في سوق الحميدية',
        notesEn: 'Shopping at Souq Al-Hamidiyah',
        createdAt: now,
        updatedAt: now,
      },
      {
        itineraryDayId: insertedDays[1]._id,
        placeId: '507f1f77bcf86cd799439025',
        order: 2,
        startTime: '11:30',
        endTime: '13:30',
        activityType: 'visit',
        notesAr: 'زيارة متحف دمشق',
        notesEn: 'Visit Damascus Museum',
        createdAt: now,
        updatedAt: now,
      },
      // Romantic Weekend - Day 1
      {
        itineraryDayId: insertedDays[2]._id,
        placeId: '507f1f77bcf86cd799439033',
        order: 1,
        startTime: '18:00',
        endTime: '20:00',
        activityType: 'dining',
        notesAr: 'عشاء رومانسي في مقهى تقليدي',
        notesEn: 'Romantic dinner at traditional cafe',
        createdAt: now,
        updatedAt: now,
      },
    ];

    await ItineraryItem.insertMany(itineraryItems);
    console.log('✅ Itinerary Items bulk-inserted (6 items)');

    // Chats and Messages - 5+ conversations
    const chats = [
      { userId: '507f1f77bcf86cd799439011', subject: 'سؤال عن ساعات العمل', status: 'closed', createdAt: now },
      { userId: '507f1f77bcf86cd799439012', subject: 'حجز فندق', status: 'active', createdAt: now },
      { userId: '507f1f77bcf86cd799439013', subject: 'معلومات عن المتاحف', status: 'active', createdAt: now },
      { userId: '507f1f77bcf86cd799439014', subject: 'رحلة جماعية', status: 'active', createdAt: now },
      { userId: '507f1f77bcf86cd799439015', subject: 'أسعار المطاعم', status: 'closed', createdAt: now },
    ];

    const insertedChats = await Chat.insertMany(chats);
    console.log('✅ Chats bulk-inserted (5 chats)');

    const messages = [
      // Chat 1 - Hours inquiry
      { chatId: insertedChats[0]._id, senderId: '507f1f77bcf86cd799439011', content: 'هل يفتح الجامع الأموي يوم الجمعة؟', messageType: 'text', isRead: true, createdAt: now },
      { chatId: insertedChats[0]._id, senderId: '507f1f77bcf86cd799439013', content: 'نعم، الجامع الأموي يفتح يوم الجمعة من الساعة 8 صباحاً حتى 2 ظهراً', messageType: 'text', isRead: false, createdAt: now },

      // Chat 2 - Hotel booking
      { chatId: insertedChats[1]._id, senderId: '507f1f77bcf86cd799439012', content: 'أريد حجز غرفة في فندق فاخر لمدة 3 أيام', messageType: 'text', isRead: true, createdAt: now },
      { chatId: insertedChats[1]._id, senderId: '507f1f77bcf86cd799439013', content: 'بالتأكيد، يمكننا مساعدتك في حجز غرفة في أحد الفنادق الفاخرة. ما هي التواريخ المطلوبة؟', messageType: 'text', isRead: false, createdAt: now },

      // Chat 3 - Museum info
      { chatId: insertedChats[2]._id, senderId: '507f1f77bcf86cd799439013', content: 'ما هي أفضل المتاحف في دمشق؟', messageType: 'text', isRead: true, createdAt: now },
      { chatId: insertedChats[2]._id, senderId: '507f1f77bcf86cd799439013', content: 'أفضل المتاحف تشمل متحف دمشق الوطني، متحف الفن الحديث، ومتحف الحرف التقليدية', messageType: 'text', isRead: false, createdAt: now },

      // Chat 4 - Group tour
      { chatId: insertedChats[3]._id, senderId: '507f1f77bcf86cd799439014', content: 'هل تقدمون رحلات جماعية للمدارس؟', messageType: 'text', isRead: true, createdAt: now },
      { chatId: insertedChats[3]._id, senderId: '507f1f77bcf86cd799439013', content: 'نعم، نقدم رحلات تعليمية خاصة للمدارس والجامعات مع دليل متخصص', messageType: 'text', isRead: false, createdAt: now },

      // Chat 5 - Restaurant prices
      { chatId: insertedChats[4]._id, senderId: '507f1f77bcf86cd799439015', content: 'ما هي أسعار الطعام في المطاعم الدمشقية؟', messageType: 'text', isRead: true, createdAt: now },
      { chatId: insertedChats[4]._id, senderId: '507f1f77bcf86cd799439013', content: 'تختلف الأسعار حسب نوع المطعم، لكن متوسط سعر الوجبة يتراوح بين 20,000 - 50,000 ليرة سورية', messageType: 'text', isRead: false, createdAt: now },
    ];

    await Message.insertMany(messages);
    console.log('✅ Messages bulk-inserted (10 messages)');

    // Notifications - 15+ notifications
    const notifications = [
      // User notifications
      {
        userId: '507f1f77bcf86cd799439011',
        type: 'booking',
        titleAr: 'تم تأكيد الحجز',
        titleEn: 'Booking Confirmed',
        messageAr: 'تم تأكيد حجزك في الجامع الأموي',
        messageEn: 'Your booking at Umayyad Mosque has been confirmed',
        isRead: false,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439011',
        type: 'review',
        titleAr: 'تذكير بكتابة تقييم',
        titleEn: 'Review Reminder',
        messageAr: 'لا تنس كتابة تقييم لزيارتك الأخيرة',
        messageEn: 'Don\'t forget to write a review for your recent visit',
        isRead: true,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439012',
        type: 'promotion',
        titleAr: 'عرض خاص',
        titleEn: 'Special Offer',
        messageAr: 'خصم 20% على حجوزات الفنادق هذا الأسبوع',
        messageEn: '20% discount on hotel bookings this week',
        isRead: false,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439013',
        type: 'alert',
        titleAr: 'تذكير بالحدث',
        titleEn: 'Event Reminder',
        messageAr: 'معرض الفن الحديث يبدأ غداً',
        messageEn: 'Modern Art Exhibition starts tomorrow',
        isRead: false,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439014',
        type: 'booking',
        titleAr: 'تذكير بالحجز',
        titleEn: 'Booking Reminder',
        messageAr: 'حجزك في مركز الاسترخاء بعد يومين',
        messageEn: 'Your spa booking is in 2 days',
        isRead: true,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439015',
        type: 'message',
        titleAr: 'رسالة جديدة',
        titleEn: 'New Message',
        messageAr: 'لديك رسالة جديدة من خدمة العملاء',
        messageEn: 'You have a new message from customer service',
        isRead: false,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439016',
        type: 'alert',
        titleAr: 'تحديث الرحلة',
        titleEn: 'Itinerary Update',
        messageAr: 'تم تحديث رحلتك المخططة',
        messageEn: 'Your planned itinerary has been updated',
        isRead: false,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439017',
        type: 'message',
        titleAr: 'تمت الإضافة للمفضلة',
        titleEn: 'Added to Favorites',
        messageAr: 'تم إضافة المقهى الرومانسي لمفضلتك',
        messageEn: 'Romantic cafe added to your favorites',
        isRead: true,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439018',
        type: 'review',
        titleAr: 'تقييم جديد',
        titleEn: 'New Review',
        messageAr: 'حصل مكانك المفضل على تقييم جديد',
        messageEn: 'Your favorite place received a new review',
        isRead: false,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439019',
        type: 'system',
        titleAr: 'تحديث النظام',
        titleEn: 'System Update',
        messageAr: 'تم تحديث التطبيق بميزات جديدة',
        messageEn: 'App updated with new features',
        isRead: true,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439020',
        type: 'alert',
        titleAr: 'تم الدفع بنجاح',
        titleEn: 'Payment Successful',
        messageAr: 'تم استلام دفعة حجزك بنجاح',
        messageEn: 'Your booking payment has been received successfully',
        isRead: false,
        createdAt: now,
      },
      // Admin notifications
      {
        userId: '507f1f77bcf86cd799439013', // Admin user
        type: 'alert',
        titleAr: 'تنبيه إداري',
        titleEn: 'Admin Alert',
        messageAr: 'تم إضافة 5 حجوزات جديدة اليوم',
        messageEn: '5 new bookings added today',
        isRead: false,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439013', // Admin user
        type: 'alert',
        titleAr: 'تقرير يومي',
        titleEn: 'Daily Report',
        messageAr: 'تم نشر 3 تقييمات جديدة',
        messageEn: '3 new reviews published',
        isRead: true,
        createdAt: now,
      },
      {
        userId: '507f1f77bcf86cd799439013', // Admin user
        type: 'alert',
        titleAr: 'تنبيه أمني',
        titleEn: 'Security Alert',
        messageAr: 'تم تسجيل دخول مشبوه',
        messageEn: 'Suspicious login detected',
        isRead: false,
        createdAt: now,
      },
    ];

    await Notification.insertMany(notifications);
    console.log('✅ Notifications bulk-inserted (15+ notifications)');

    console.log('🎉 Database seeding completed successfully!');

  } catch (error) {
    console.error('❌ Error seeding database (fixed):', error);
  }
};
